### ISSUE TITLE
In/out solution with web MIDI?

### ISSUE THREAD

**Issue by Jonathhhan** [ircam-jstools/node-libpd#2]
Hi,
very interesting project, does that mean it is possible to run pd vanilla patches on the web (that would be great)?
Regarding the in / out todo: I just made some experiments with web MIDI, perhaps that could be a way.
Here is my example where you can choose midi in and out port:
https://webmidi.handmadeproductions.de/
In this example the microphone input is used with web Audio, I do not know if that helps for getting audio in in your project: https://github.com/jberg/butterchurn/tree/master/examples

**Comment by b-ma** [comment]
Hey, 

Sorry for the late reply, 
This library is meant to be used within Node.js, it cannot run in a browser (and never will). I guess it answers all your questions.

Best,

**Comment by Jonathhhan** [comment]
Thanks, yes that answers my question.
Meanwhile I found a solution with Emscripten and Ofelia:
https://pdmidi.handmadeproductions.de/
https://pdspectrum.handmadeproductions.de/
